language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - wget https://github.com/gitbucket/gitbucket/releases/download/4.11/gitbucket.war
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mkdir -p ~/.gitbucket/plugins
  - wget -P ~/.gitbucket/plugins https://github.com/kounoike/gitbucket-ipynb-plugin/releases/download/0.1.1/gitbucket-ipynb-plugin_2.12-0.1.1.jar
  - ls -laR
  - java -jar gitbucket.war &
  - sleep 30

script:
  - sbt -Dwebdriver.chrome.driver=chromedriver test