language: scala
scala:
    - 2.12.1
jdk:
    - oraclejdk8

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - wget https://github.com/gitbucket/gitbucket/releases/download/4.11/gitbucket.war
    - mkdir -p ~/.gitbucket/plugins
    - wget -P ~/.gitbucket/plugins https://github.com/kounoike/gitbucket-ipynb-plugin/releases/download/0.1.1/gitbucket-ipynb-plugin_2.12-0.1.1.jar
    - ls -lR
    - java -jar gitbucket.war &
    - sleep 30

script:
    - sbt test